# Generated by Django 5.1.1 on 2025-01-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_osoba_data_dodania'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osoba',
            name='data_dodania',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='imie',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='nazwisko',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='plec',
            field=models.CharField(choices=[('K', 'Kobieta'), ('M', 'Męczyzna '), ('I', 'Inne')], default='I', max_length=1),
        ),
        migrations.AlterField(
            model_name='stanowisko',
            name='nazwa',
            field=models.CharField(max_length=100),
        ),
    ]
